import { CATEGORY_LABEL, CATEGORY_ORDER, type Category, type Finding, type Report } from "./types";

const SEVERITY_ICON: Record<string, string> = {
  error: "error",
  warning: "warning",
  info: "info",
  pass: "pass",
};

export function toMarkdown(report: Report): string {
  const lines: string[] = [];
  lines.push(`# OGraf package check — ${report.pkgName}`);
  lines.push("");
  lines.push(`- **Size:** ${(report.pkgSize / 1024).toFixed(1)} KB`);
  lines.push(`- **Checked in:** ${report.durationMs.toFixed(1)} ms`);
  lines.push(`- **Errors:** ${report.summary.errors} · **Warnings:** ${report.summary.warnings} · **Info:** ${report.summary.infos} · **Passes:** ${report.summary.passes}`);
  lines.push(`- **Validated against:** ${report.schemaSource.url} (${report.schemaSource.kind})`);
  lines.push(`- **Fetched at:** ${report.schemaSource.fetchedAt}`);
  if (report.schemaSource.note) lines.push(`- **Note:** ${report.schemaSource.note}`);
  lines.push("");

  const byCategory = groupByCategory(report.findings);
  for (const category of CATEGORY_ORDER) {
    const findings = byCategory.get(category);
    if (!findings || findings.length === 0) continue;
    lines.push(`## ${CATEGORY_LABEL[category]}`);
    lines.push("");
    for (const f of findings) {
      const icon = SEVERITY_ICON[f.severity] ?? f.severity;
      lines.push(`- **[${f.id}] ${icon.toUpperCase()}** — ${f.title}`);
      if (f.path) lines.push(`  - path: \`${f.path}\``);
      lines.push(`  - ${f.message.replace(/\n+/g, " ")}`);
      if (f.specRef) lines.push(`  - spec: ${f.specRef}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("Generated by the OGraf Package Checker on https://ograf.dev/check");
  return lines.join("\n") + "\n";
}

function groupByCategory(findings: readonly Finding[]): Map<Category, Finding[]> {
  const map = new Map<Category, Finding[]>();
  for (const f of findings) {
    const arr = map.get(f.category) ?? [];
    arr.push(f);
    map.set(f.category, arr);
  }
  return map;
}
