/**
 * Merges two data sources:
 *
 *  - specThreads.json     — raw GitHub data (regenerated by scripts/refresh-spec-history.sh)
 *  - specSummaries.json   — hand-curated plain-English summaries + merged-PR references
 *                           (survives refresh; edit by hand as new issues close)
 *
 * After refreshing specThreads.json, add an entry to specSummaries.json for any
 * new issue numbers that appear. Issues without a summary fall back to the
 * GitHub title.
 */

import threadsJson from "./specThreads.json";
import summariesJson from "./specSummaries.json";

export interface ThreadComment {
  author: string;
  createdAt: string;
  body: string;
}

export interface SpecThread {
  number: number;
  title: string;
  url: string;
  closedAt: string;
  author: string;
  labels: string[];
  body: string;
  comments: ThreadComment[];
}

interface SpecSummary {
  summary: string;
  mergedBy?: number;
}

export interface SpecHistoryEntry extends SpecThread {
  summary: string;
  mergedBy?: number;
}

const threads = threadsJson as SpecThread[];
const summaries = summariesJson as Record<string, SpecSummary>;

export const SPEC_HISTORY: SpecHistoryEntry[] = threads.map((thread) => {
  const curated = summaries[String(thread.number)];
  return {
    ...thread,
    summary: curated?.summary ?? thread.title,
    mergedBy: curated?.mergedBy,
  };
});
